name: CI

on: push

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          job_recommender:
            - 'src/projects/job_recommender/**'
          position_recommender:
            - 'src/projects/position_recommender/**'

  # JOB to build and test backend code
  job_recommender:
    needs: changes
    if: ${{ needs.changes.outputs.job_recommender == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  # JOB to build and test frontend code
  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.position_recommender == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
